name: theme_demo
description: A new Flutter template.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.5+2

environment:
  sdk: ">=3.2.3 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.16.8"

dependencies:
  flutter:
    sdk: flutter
  ##app_settings: ^5.1.1 # A Flutter plugin for opening iOS and Android phone settings from an app.
  ##cupertino_icons: ^1.0.6 # This is an asset repo for Cupertino widgets.
  flutter_bloc: ^8.1.5 # A predictable state management library that helps implement the BLoC design pattern
  flutter_modular: ^6.3.2 # Smart project structure with dependency injection and route management
  # nosql_dart:
  #   git: https://github.com/GitHubStuff/nosql_dart.git
  ui_extensions_flutter:
    git: https://github.com/GitHubStuff/ui_extensions_flutter.git
  ui_theme_mode_flutter:
    path: ../../ui_theme_mode_flutter

# dart run build_runner build -d
dev_dependencies:
  build_runner: ^2.4.9 # provides a concrete way of generating files using Dart code
  flutter_gen_runner: ^5.4.0 # The Flutter code generator for your assets, fonts, colors
  flutter_launcher_icons: ^0.13.1 # A command-line tool that simplifies updating Flutter app's launcher icon
  flutter_lints: ^3.0.1
  flutter_test: # Testing library for flutter, built on top of package:test.
    sdk: flutter

# Element of flutter_launcher_icons https://pub.dev/packages/flutter_launcher_icons
# '% dart run flutter_launcher_icons'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/rainbow.png"
  macos:
    generate: true
    image_path: "assets/images/rainbow.png"
  web:
    generate: true
    image_path: "assets/images/rainbow.png"
  windows:
    generate: true
    image_path: "assets/images/rainbow.png"

# Element of flutter_gen https://pub.dev/packages/flutter_gen/install
# '% dart pub global activate flutter_gen'
# '% fluttergen'
flutter_gen:
  line_length: 132

flutter:
  uses-material-design: true
  assets:
    - assets/images/
