name: ui_theme_mode_flutter
description: "Controls/Persists/Notifies of changes in theme"
version: 0.0.5+7
home_page: http://www.icodeforyou.com
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0" # % flutter --version => values of "Dart"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_modular: ^6.3.3
  hive_flutter: ^1.1.0
  nosql_dart:
    git: https://github.com/GitHubStuff/nosql_dart.git
    #path: ../nosql_dart
  ui_shared:
    git: https://github.com/GitHubStuff/ui_shared_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  mockito: ^5.4.4 # Mock library for Dart inspired by Mockito.
  file: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
